const express = require("express");
const router = express.Router();
const projectController = require("../controllers/projectController");

router.get("/", projectController.getProjects);
router.get("/kanban:id", projectController.getKanban);
router.put("/kanban:id", projectController.updateKanban);
router.get("/kanban/:id/assignee", projectController.getAssignee);
router.get("/kanban/:id/isAdmin", projectController.isAdmin);
// router.get('/CFD', projectController.getCFD);
// router.get('/burnup', projectController.getBurnup);
// router.get('/taskAging', projectController.getTaskAging);
// router.get("/new", projectController.newProject);
router.post("/createProject", projectController.createProject);
router.get("/:id", projectController.getProject);
router.put("/addUser", projectController.addUser);
router.put("/ageNotification", projectController.ageNotification);
// router.get('/:id/getProjectInfo', projectController.getProjectInfo);
router.get("/:id/edit", projectController.edit);
router.put("/:id", projectController.updateProject);
router.delete("/:id", projectController.deleteProject);
router.get("/kanban/:id/data", projectController.getKanbanData);
module.exports = router;
